/**
 * Explore Tsunami Risk Along India's Coastline
 * Core Interactive Logic & Oceanographic Data System
 * Incredible India Explorer
 */

export const TSUNAMI_DATA = {
    title: "Explore Tsunami Risk Along India's Coastline",
    subtitle: "Understanding Subduction Zone Tectonics, Wave Shoaling Physics, Early Warning Systems, and Coastal Safety Across India's 7,516 km Coastline",
    coastlineLength: "7,516 km",
    subductionZones: "2 Active Trenches",
    warningTimeINCOIS: "< 10 Minutes",
    baselineEvent: "2004 Indian Ocean Tsunami",

    mechanics: [
        {
            id: "subduction-megathrust",
            title: "Megathrust Earthquakes",
            icon: "🌋",
            summary: "Vertical sea floor displacement at subduction zones drives massive water columns.",
            description: "Tsunamis are most frequently generated by sudden vertical displacement of the seafloor during megathrust earthquakes at subduction zone plate boundaries (such as where the Indo-Australian Plate subducts beneath the Sunda Plate). The sudden upward movement displaces thousands of cubic kilometers of ocean water."
        },
        {
            id: "open-ocean-speed",
            title: "Deep Ocean Propagation",
            icon: "🚀",
            summary: "Travels at jet-airliner speeds (~700–800 km/h) with barely noticeable surface height.",
            description: "In deep ocean waters (>4,000 meters deep), tsunami waves possess vast wavelengths (100–200 km) and low wave amplitudes (<1 meter). They travel at speeds exceeding 700 to 800 km/h without losing significant energy, remaining virtually unnoticeable to ships at sea."
        },
        {
            id: "shoaling-amplification",
            title: "Shallow-Water Shoaling",
            icon: "🌊",
            summary: "Wave speed decreases, wavelength compresses, and wave height explodes shoreward.",
            description: "As the tsunami wave enters shallow coastal waters, friction with the seabed slows the wave front to 30–50 km/h. The trailing wave energy compresses the volume, forcing the water amplitude to surge upwards into destructive walls of water 5 to 30 meters high."
        },
        {
            id: "coastal-drawdown",
            title: "Initial Water Drawdown",
            icon: "🏖️",
            summary: "Trough arrival causes sea water to rapidly recede, exposing intertidal seabeds.",
            description: "If the trough of the tsunami wave reaches land first, the ocean recedes dramatically hundreds of meters offshore within minutes, exposing reefs and seafloors. This is a critical natural warning sign of an impending crest arrival within minutes."
        },
        {
            id: "wave-trains",
            title: "Multiple Wave Trains",
            icon: "🔄",
            summary: "A tsunami is a series of waves; the first wave is rarely the largest.",
            description: "Tsunamis strike as a succession of waves (a wave train) spaced 10 to 60 minutes apart. The second, third, or fourth surge is frequently much larger and more destructive than the initial surge wave."
        }
    ],

    coastalZones: [
        {
            id: "andaman-nicobar",
            name: "Andaman & Nicobar Islands",
            region: "Bay of Bengal (Direct Fault Contact)",
            riskLevel: "Critical Risk",
            riskColor: "#ef4444",
            lat: 11.62,
            lng: 92.72,
            threatSource: "Andaman-Sumatra Subduction Zone",
            arrivalLeadTime: "5 to 25 minutes",
            historicMaxRunup: "15.0–30.0 m (2004 Tsunami)",
            description: "Sitting directly atop the boundary between the India/Australian and Burma microplates, the island archipelago is vulnerable to immediate near-field tsunamis within minutes of a megathrust earthquake."
        },
        {
            id: "nagapattinam",
            name: "Nagapattinam & Coromandel Coast",
            region: "Tamil Nadu (Bay of Bengal)",
            riskLevel: "Very High",
            riskColor: "#ef4444",
            lat: 10.76,
            lng: 79.84,
            threatSource: "Andaman-Sumatra Subduction Zone",
            arrivalLeadTime: "2.0 to 2.5 hours",
            historicMaxRunup: "6.0–12.0 m (2004 Tsunami)",
            description: "Low-elevation deltaic coastal terrain suffered extreme devastation during the 2004 Boxing Day Tsunami, leading to major coastal bio-shield restoration and early warning installation."
        },
        {
            id: "kanyakumari",
            name: "Kanyakumari & Southern Apex",
            region: "Tamil Nadu (Indian Ocean Apex)",
            riskLevel: "Very High",
            riskColor: "#ef4444",
            lat: 8.08,
            lng: 77.53,
            threatSource: "Andaman-Sumatra Subduction Zone",
            arrivalLeadTime: "2.5 to 3.0 hours",
            historicMaxRunup: "6.0–10.0 m (2004 Tsunami)",
            description: "Where the Bay of Bengal, Arabian Sea, and Indian Ocean converge. Wave wrapping and diffraction effects caused devastating run-up heights in 2004."
        },
        {
            id: "machilipatnam",
            name: "Machilipatnam & Andhra Deltas",
            region: "Andhra Pradesh (Bay of Bengal)",
            riskLevel: "High",
            riskColor: "#f97316",
            lat: 16.18,
            lng: 81.13,
            threatSource: "Andaman-Sumatra Subduction Zone",
            arrivalLeadTime: "2.5 to 3.5 hours",
            historicMaxRunup: "3.0–5.0 m (2004 Tsunami)",
            description: "Flat deltaic plains of the Krishna and Godavari rivers allow tsunami waves to drive kilometers inland, threatening aquaculture and fishing settlements."
        },
        {
            id: "gujarat-kutch",
            name: "Gulf of Kutch & Saurashtra",
            region: "Gujarat (Arabian Sea)",
            riskLevel: "High",
            riskColor: "#f97316",
            lat: 22.47,
            lng: 69.06,
            threatSource: "Makran Subduction Zone",
            arrivalLeadTime: "1.5 to 2.5 hours",
            historicMaxRunup: "2.5–4.0 m (1945 Makran Tsunami)",
            description: "Vulnerable to megathrust earthquakes generated along the Makran fault line off Pakistan/Iran. In 1945, tsunami waves struck Kandla port and salt flats."
        },
        {
            id: "mumbai-konkan",
            name: "Mumbai & Konkan Coast",
            region: "Maharashtra (Arabian Sea)",
            riskLevel: "Moderate to High",
            riskColor: "#eab308",
            lat: 18.96,
            lng: 72.82,
            threatSource: "Makran Subduction Zone",
            arrivalLeadTime: "3.0 to 4.0 hours",
            historicMaxRunup: "2.0–3.0 m (1945 Makran Tsunami)",
            description: "Dense coastal population infrastructure makes even moderate tsunami run-up heights (2-3m) high-impact events for Mumbai's harbor and low-lying reclamation zones."
        },
        {
            id: "kerala-malabar",
            name: "Kollam & Malabar Coast",
            region: "Kerala (Arabian Sea)",
            riskLevel: "High",
            riskColor: "#f97316",
            lat: 8.89,
            lng: 76.58,
            threatSource: "Andaman-Sumatra (Diffracted) / Makran",
            arrivalLeadTime: "3.5 to 4.0 hours",
            historicMaxRunup: "3.0–5.0 m (2004 Tsunami diffracted around Sri Lanka)",
            description: "Despite facing the Arabian Sea, southern Kerala suffered severe wave impact in 2004 due to wave diffraction around Sri Lanka's southern tip."
        }
    ],

    historicalEvents: [
        {
            year: "2004",
            name: "Indian Ocean Tsunami (Boxing Day)",
            magnitude: "Mw 9.1 – 9.3",
            sourceFault: "Andaman-Sumatra Subduction Zone",
            maxRunup: "15.0 – 30.0 meters",
            fatalitiesIndia: "10,000+ (18,000+ total including missing)",
            impact: "World's most devastating tsunami in modern history. Triggered by a megathrust earthquake off Northern Sumatra, generating trans-oceanic wave trains that struck Andaman & Nicobar, Tamil Nadu (Nagapattinam/Kanyakumari), Andhra Pradesh, and Kerala within 2 to 3.5 hours.",
            badgeColor: "critical"
        },
        {
            year: "1945",
            name: "Makran Earthquake Tsunami",
            magnitude: "Mw 8.1",
            sourceFault: "Makran Subduction Zone (Arabian Sea)",
            maxRunup: "3.0 – 12.0 meters (Pasni) / 2.0-3.5m (India)",
            fatalitiesIndia: "~4,000 across region (12+ in Mumbai)",
            impact: "Earthquake centered off Pasni, Pakistan generated a powerful tsunami in the Arabian Sea. Tsunami waves swept over ports in Gujarat (Kandla) and arrived at Mumbai harbor, damaging boats and coastal infrastructure.",
            badgeColor: "warning"
        },
        {
            year: "1881",
            name: "Great Car Nicobar Earthquake",
            magnitude: "Mw 7.9",
            sourceFault: "Andaman-Sumatra Subduction Zone",
            maxRunup: "1.0 – 1.5 meters",
            fatalitiesIndia: "Minimal (Recorded on tide gauges)",
            impact: "Earthquake centered near Car Nicobar Island generated tsunami waves that were recorded across the Bay of Bengal by historical tide gauges in Chennai (Madras) and Nagapattinam.",
            badgeColor: "info"
        },
        {
            year: "1941",
            name: "Andaman Archipelago Earthquake",
            magnitude: "Mw 7.7",
            sourceFault: "Andaman-Nicobar Trench",
            maxRunup: "0.7 – 1.2 meters",
            fatalitiesIndia: "Localized impact in Andaman Islands",
            impact: "Occurred during World War II in the Andaman Sea, causing localized tsunami inundation along island coasts and recorded wave anomalies along the Coromandel coast.",
            badgeColor: "info"
        }
    ],

    subductionComparison: {
        andamanSumatra: {
            title: "Andaman-Sumatra Subduction Zone (Bay of Bengal)",
            plateBoundary: "Indo-Australian Plate subducting beneath the Burma Microplate / Sunda Plate",
            trenchLength: "~5,500 km arc length",
            maxSeismicPotential: "Mw 9.0 to 9.3 Megathrust events",
            mainlandLeadTime: "2.0 to 3.0 hours to East Coast (Tamil Nadu, AP, Odisha)",
            historicalFrequency: "High frequency of major megathrust events (1881, 1941, 2004)",
            threatenedStates: "Andaman & Nicobar Islands, Tamil Nadu, Puducherry, Andhra Pradesh, Odisha, West Bengal"
        },
        makranZone: {
            title: "Makran Subduction Zone (Arabian Sea)",
            plateBoundary: "Arabian Plate subducting beneath the Eurasian Plate",
            trenchLength: "~900 km length off Pakistan/Iran coast",
            maxSeismicPotential: "Mw 8.0 to 8.5 Megathrust events",
            mainlandLeadTime: "1.5 to 3.5 hours to West Coast (Gujarat, Maharashtra)",
            historicalFrequency: "Lower historical frequency, but capable of generating major Arabian Sea tsunamis (1945)",
            threatenedStates: "Gujarat (Gulf of Kutch/Khambhat), Maharashtra (Mumbai), Goa, Karnataka, Kerala"
        }
    },

    earlyWarningSystem: [
        {
            title: "INCOIS Tsunami Early Warning Center (ITEWS)",
            category: "Operational Warning System",
            icon: "🛰️",
            description: "Established at INCOIS in Hyderabad following the 2004 disaster, ITEWS operates 24x7 using real-time seismic networks, Bottom Pressure Recorders (BPRs), ocean buoys, and tide gauges to issue location-specific tsunami advisories within 10 minutes of a major earthquake."
        },
        {
            title: "Bottom Pressure Recorders (BPR Tsunameters)",
            category: "Deep-Ocean Sensor Network",
            icon: "⚓",
            description: "Deployed in deep waters of the Bay of Bengal and Arabian Sea, BPRs detect subtle pressure changes of passing tsunami waves (<1 cm) on the ocean floor and transmit real-time wave telemetry to satellites."
        },
        {
            title: "UNESCO Tsunami Ready Program",
            category: "Community Resilience",
            icon: "🏅",
            description: "Odisha became the first region in the Indian Ocean rim to have coastal communities (such as Venkatraipur in Ganjam and Noliasahi in Jagatsinghpur) certified under the UNESCO-IOC Tsunami Ready Program, equipped with evacuation maps, sirens, and community drills."
        },
        {
            title: "Coastal Bio-Shields & Dune Defense",
            category: "Nature-Based Solution",
            icon: "🌿",
            description: "Restoration of coastal mangrove belts (Sundarbans, Pichavaram) and Casuarina tree plantations along sandy beaches dissipates incoming wave momentum and reduces inland run-up distance during tsunami inundation."
        }
    ],

    quizQuestions: [
        {
            question: "What is the primary physical cause of major ocean-wide tsunamis in India?",
            options: [
                "Strong monsoon wind gusts",
                "Subduction zone megathrust earthquakes causing vertical seafloor displacement",
                "High astronomical spring tides",
                "Undersea coral reef growth"
            ],
            correct: 1,
            explanation: "Tsunamis are generated when vertical displacement of the seafloor during megathrust earthquakes displaces thousands of cubic kilometers of ocean water."
        },
        {
            question: "Why do tsunami waves become dangerously tall as they approach shallow coastal waters (shoaling)?",
            options: [
                "Because ocean water gets warmer near the coast",
                "Because friction with the shallow seabed slows the wave front, compressing wave energy upward",
                "Because coastal winds push the wave from behind",
                "Because rivers push freshwater into the ocean"
            ],
            correct: 1,
            explanation: "As shallow water slows the leading edge of the wave to 30-50 km/h, the massive wave volume behind compresses and surges upward into high run-up waves."
        },
        {
            question: "What is a critical natural warning sign of an impending tsunami crest arrival?",
            options: [
                "Rapid, sudden withdrawal/retreat of ocean water exposing seafloors",
                "Heavy monsoon rainfall",
                "Sudden drop in atmospheric temperature",
                "Formation of thick sea fog"
            ],
            correct: 0,
            explanation: "If the trough of a tsunami wave arrives first, the sea recedes rapidly offshore, leaving reefs exposed—an urgent signal to run inland immediately."
        },
        {
            question: "Which Indian organization operates the 24x7 Indian Tsunami Early Warning System (ITEWS)?",
            options: [
                "INCOIS (Indian National Centre for Ocean Information Services)",
                "ISRO",
                "NDRF",
                "IMD"
            ],
            correct: 0,
            explanation: "INCOIS Hyderabad operates ITEWS, utilizing seismic, BPR, and tide gauge networks to issue early warnings within 10 minutes of undersea earthquakes."
        }
    ]
};

// Application State & Interactive Logic Initialization
document.addEventListener("DOMContentLoaded", () => {
    initSimulator();
    initMap();
    renderTimeline("all");
    initTabs();
    initQuiz();
    initThemeToggle();
    initMobileNav();
});

// Interactive Tsunami Wave Propagation Simulator
function initSimulator() {
    const magInput = document.getElementById("sim-mag");
    const sourceSelect = document.getElementById("sim-source");
    const distInput = document.getElementById("sim-dist");

    const magValSpan = document.getElementById("val-mag");
    const sourceValSpan = document.getElementById("val-source");
    const distValSpan = document.getElementById("val-dist");

    const speedResultElem = document.getElementById("wave-speed-result");
    const travelTimeResultElem = document.getElementById("travel-time-result");
    const runupResultElem = document.getElementById("runup-height-result");
    const riskBadgeElem = document.getElementById("tsunami-risk-badge");
    const advisoryElem = document.getElementById("tsunami-advisory");

    if (!magInput || !sourceSelect || !distInput) return;

    function calculateTsunami() {
        const mag = parseFloat(magInput.value); // 7.0 to 9.3
        const source = sourceSelect.value; // 'andaman', 'makran'
        const distanceKm = parseInt(distInput.value, 10); // 100 to 2000

        magValSpan.textContent = `Mw ${mag.toFixed(1)}`;
        distValSpan.textContent = `${distanceKm} km`;

        let sourceLabel = "Andaman-Sumatra Subduction Zone";
        let avgOceanDepthM = 3800;
        if (source === "makran") {
            sourceLabel = "Makran Subduction Zone (Arabian Sea)";
            avgOceanDepthM = 3000;
        }
        sourceValSpan.textContent = sourceLabel;

        // Wave speed formula: v = sqrt(g * d) where g=9.81 m/s^2, d=depth in meters
        const waveSpeedMS = Math.sqrt(9.81 * avgOceanDepthM);
        const waveSpeedKmH = Math.round(waveSpeedMS * 3.6); // ~700-750 km/h

        // Travel time: distance / speed
        const travelTimeHoursDecimal = distanceKm / waveSpeedKmH;
        const totalMinutes = Math.round(travelTimeHoursDecimal * 60);
        const hours = Math.floor(totalMinutes / 60);
        const mins = totalMinutes % 60;
        const timeFormatted = hours > 0 ? `${hours}h ${mins}m` : `${mins} mins`;

        // Runup height exponential scaling with Mw magnitude:
        // Mw 7.0 -> ~0.8m, Mw 8.0 -> ~3.5m, Mw 9.0 -> ~14m, Mw 9.3 -> ~24m
        const energyScale = Math.pow(10, 1.5 * (mag - 7.0));
        const distanceDecay = Math.max(0.3, Math.pow(1000 / Math.max(200, distanceKm), 0.5));
        const estimatedRunupM = Math.min(32.0, (0.75 * Math.pow(energyScale, 0.42) * distanceDecay)).toFixed(1);

        speedResultElem.textContent = `${waveSpeedKmH} km/h`;
        travelTimeResultElem.textContent = timeFormatted;
        runupResultElem.textContent = `${estimatedRunupM} m`;

        if (estimatedRunupM >= 8.0) {
            riskBadgeElem.textContent = "CRITICAL / TSUNAMI WARNING";
            riskBadgeElem.className = "risk-pill critical";
            advisoryElem.innerHTML = "<strong>Major Tsunami Warning:</strong> Catastrophic wave inundation expected. Complete immediate vertical or high-ground inland evacuation beyond 2 km from shore.";
        } else if (estimatedRunupM >= 3.0) {
            riskBadgeElem.textContent = "HIGH TSUNAMI HAZARD";
            riskBadgeElem.className = "risk-pill high";
            advisoryElem.innerHTML = "<strong>Tsunami Warning:</strong> Destructive coastal waves will flood beaches, ports, and low-lying coastal roads. Move inland and to elevated ground immediately.";
        } else if (estimatedRunupM >= 1.0) {
            riskBadgeElem.textContent = "TSUNAMI ADVISORY";
            riskBadgeElem.className = "risk-pill moderate";
            advisoryElem.innerHTML = "<strong>Tsunami Advisory:</strong> Strong currents and dangerous sea level fluctuations expected in harbors and intertidal zones. Stay off beaches and out of water.";
        } else {
            riskBadgeElem.textContent = "LOW TSUNAMI IMPACT";
            riskBadgeElem.className = "risk-pill low";
            advisoryElem.innerHTML = "<strong>Minor Sea Level Anomaly:</strong> Minor wave activity confined to deep water; minimal land threat.";
        }
    }

    magInput.addEventListener("input", calculateTsunami);
    sourceSelect.addEventListener("change", calculateTsunami);
    distInput.addEventListener("input", calculateTsunami);

    calculateTsunami();
}

// Leaflet Map Initialization
function initMap() {
    const mapElem = document.getElementById("tsunami-map");
    if (!mapElem || typeof L === "undefined") return;

    const map = L.map("tsunami-map", {
        center: [14.0, 82.0],
        zoom: 4.5,
        scrollWheelZoom: false
    });

    L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png", {
        maxZoom: 18,
        attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
    }).addTo(map);

    // Plot Coastal Zones
    TSUNAMI_DATA.coastalZones.forEach(zone => {
        const marker = L.circleMarker([zone.lat, zone.lng], {
            radius: zone.riskLevel === "Critical Risk" ? 12 : (zone.riskLevel === "Very High" ? 10 : 8),
            fillColor: zone.riskColor,
            color: "#ffffff",
            weight: 2,
            opacity: 1,
            fillOpacity: 0.85
        }).addTo(map);

        const popupContent = `
            <div class="map-popup-card">
                <span class="popup-badge" style="background:${zone.riskColor}">${zone.riskLevel}</span>
                <h3>${zone.name}</h3>
                <p><strong>Region:</strong> ${zone.region}</p>
                <p><strong>Threat Source:</strong> ${zone.threatSource}</p>
                <p><strong>Lead Time:</strong> ${zone.arrivalLeadTime}</p>
                <p><strong>Historic Run-up:</strong> ${zone.historicMaxRunup}</p>
                <p class="popup-desc">${zone.description}</p>
            </div>
        `;
        marker.bindPopup(popupContent);
    });

    // Plot Andaman-Sumatra Subduction Trench Line
    const andamanTrench = [
        [3.0, 95.5], [6.0, 93.5], [9.5, 92.5], [14.0, 93.0], [18.0, 93.5]
    ];
    L.polyline(andamanTrench, {
        color: "#ef4444",
        weight: 3,
        dashArray: "6, 6"
    }).addTo(map).bindTooltip("Andaman-Sumatra Subduction Trench");

    // Plot Makran Subduction Trench Line
    const makranTrench = [
        [24.5, 62.0], [24.8, 65.0], [25.0, 67.5]
    ];
    L.polyline(makranTrench, {
        color: "#f97316",
        weight: 3,
        dashArray: "6, 6"
    }).addTo(map).bindTooltip("Makran Subduction Zone");
}

// Historical Timeline Renderer
function renderTimeline(filterCategory) {
    const container = document.getElementById("timeline-cards-container");
    if (!container) return;

    container.innerHTML = "";

    const eventsToDisplay = TSUNAMI_DATA.historicalEvents.filter(ev => {
        if (filterCategory === "all") return true;
        if (filterCategory === "andaman") return ev.sourceFault.includes("Andaman");
        if (filterCategory === "makran") return ev.sourceFault.includes("Makran");
        return true;
    });

    eventsToDisplay.forEach(ev => {
        const card = document.createElement("div");
        card.className = "timeline-card";

        let badgeClass = "badge-info";
        if (ev.badgeColor === "critical") badgeClass = "badge-critical";
        if (ev.badgeColor === "warning") badgeClass = "badge-warning";

        card.innerHTML = `
            <div class="timeline-header">
                <span class="event-year">${ev.year}</span>
                <span class="badge ${badgeClass}">${ev.magnitude}</span>
            </div>
            <h3 class="event-name">${ev.name}</h3>
            <div class="event-meta">
                <span>📍 Source: <strong>${ev.sourceFault}</strong></span>
                <span>🌊 Peak Run-up: <strong>${ev.maxRunup}</strong></span>
                <span>⚠️ Impact: ${ev.fatalitiesIndia}</span>
            </div>
            <p class="event-impact">${ev.impact}</p>
        `;
        container.appendChild(card);
    });

    const filterBtns = document.querySelectorAll(".filter-btn");
    filterBtns.forEach(btn => {
        btn.addEventListener("click", (e) => {
            filterBtns.forEach(b => b.classList.remove("active"));
            e.target.classList.add("active");
            renderTimeline(e.target.dataset.filter);
        });
    });
}

// Interactive Tabs Logic
function initTabs() {
    const tabBtns = document.querySelectorAll(".tab-btn");
    const tabPanes = document.querySelectorAll(".tab-pane");

    tabBtns.forEach(btn => {
        btn.addEventListener("click", () => {
            const targetId = btn.dataset.tab;
            tabBtns.forEach(b => b.classList.remove("active"));
            tabPanes.forEach(p => p.classList.remove("active"));

            btn.classList.add("active");
            const targetPane = document.getElementById(targetId);
            if (targetPane) targetPane.classList.add("active");
        });
    });
}

// Interactive Quiz Module
function initQuiz() {
    const quizContainer = document.getElementById("quiz-container");
    if (!quizContainer) return;

    quizContainer.innerHTML = "";

    TSUNAMI_DATA.quizQuestions.forEach((q, qIndex) => {
        const qCard = document.createElement("div");
        qCard.className = "quiz-card";

        let optionsHtml = "";
        q.options.forEach((opt, optIndex) => {
            optionsHtml += `
                <button class="quiz-option" data-q="${qIndex}" data-opt="${optIndex}">
                    ${opt}
                </button>
            `;
        });

        qCard.innerHTML = `
            <h4>Q${qIndex + 1}: ${q.question}</h4>
            <div class="quiz-options">${optionsHtml}</div>
            <div class="quiz-feedback hidden" id="feedback-${qIndex}"></div>
        `;
        quizContainer.appendChild(qCard);
    });

    quizContainer.addEventListener("click", (e) => {
        if (!e.target.classList.contains("quiz-option")) return;

        const btn = e.target;
        const qIndex = parseInt(btn.dataset.q, 10);
        const optIndex = parseInt(btn.dataset.opt, 10);
        const qData = TSUNAMI_DATA.quizQuestions[qIndex];
        const feedbackElem = document.getElementById(`feedback-${qIndex}`);

        const siblingBtns = btn.parentElement.querySelectorAll(".quiz-option");
        siblingBtns.forEach(b => {
            b.disabled = true;
            b.classList.remove("selected", "correct", "wrong");
        });

        if (optIndex === qData.correct) {
            btn.classList.add("correct");
            feedbackElem.className = "quiz-feedback success";
            feedbackElem.innerHTML = `<strong>Correct!</strong> ${qData.explanation}`;
        } else {
            btn.classList.add("wrong");
            siblingBtns[qData.correct].classList.add("correct");
            feedbackElem.className = "quiz-feedback error";
            feedbackElem.innerHTML = `<strong>Incorrect.</strong> ${qData.explanation}`;
        }
        feedbackElem.classList.remove("hidden");
    });
}

// Theme Toggle Functionality
function initThemeToggle() {
    const toggleBtn = document.getElementById("theme-toggle");
    if (!toggleBtn) return;

    toggleBtn.addEventListener("click", () => {
        const isLight = document.body.classList.toggle("light-theme");
        const newTheme = isLight ? "light" : "dark";
        localStorage.setItem("theme", newTheme);

        try {
            const iieStorage = JSON.parse(localStorage.getItem("iie_storage") || "{}");
            iieStorage.theme = newTheme;
            localStorage.setItem("iie_storage", JSON.stringify(iieStorage));
        } catch (e) {}

        toggleBtn.setAttribute("aria-label", `Switch to ${isLight ? 'dark' : 'light'} mode`);
    });
}

// Mobile Navigation Toggle
function initMobileNav() {
    const menuToggle = document.getElementById("menu-toggle");
    const navMenu = document.getElementById("nav-menu");

    if (menuToggle && navMenu) {
        menuToggle.addEventListener("click", () => {
            const expanded = menuToggle.getAttribute("aria-expanded") === "true";
            menuToggle.setAttribute("aria-expanded", !expanded);
            navMenu.classList.toggle("active");
        });
    }
}
